In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import loadtxt
test_list = [
 np.loadtxt('Test1.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Test2.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Test3.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Test4.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Test5.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Test6.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Test7.sample', delimiter= ' ', dtype=object),
]

train_list = [
 np.loadtxt('Train1.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Train2.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Train3.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Train4.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Train5.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Train6.sample', delimiter= ' ', dtype=object),
 np.loadtxt('Train7.sample', delimiter= ' ', dtype=object)
]

In [15]:
dataframe = []

all_x_train = []# Initialize lists to store data
all_y_train = []
all_x_test = []
all_y_test = []

for x in range(len(test_list)):
    train = train_list[x]
    test = test_list[x]

    all_x_train.append(x_train)# Append data to lists
    all_y_train.append(y_train)
    all_x_test.append(x_test)
    all_y_test.append(y_test)

final_x_train = np.concatenate(all_x_train, axis=0)# Concatenate lists to create final data arrays
final_y_train = np.concatenate(all_y_train, axis=0).reshape(-1, 1)
final_x_test = np.concatenate(all_x_test, axis=0)
final_y_test = np.concatenate(all_y_test, axis=0).reshape(-1, 1)

columns = [f'feature_{i}' for i in range(final_x_train.shape[1])]# Create DataFrames
df_x_train = pd.DataFrame(final_x_train, columns=columns)
df_y_train = pd.DataFrame(final_y_train, columns=['target'])
df_x_test = pd.DataFrame(final_x_test, columns=columns)
df_y_test = pd.DataFrame(final_y_test, columns=['target'])

df_train = pd.concat([df_x_train, df_y_train], axis=1)# Combine DataFrames
df_test = pd.concat([df_x_test, df_y_test], axis=1)

print(df_train.head())# Display or use df_train and df_test as needed
print(df_test.head())

  feature_0 feature_1 feature_2 feature_3 feature_4 feature_5 feature_6  \
0        38        58        11        56        45        47        18
1        17        23        58        47        47       111         2
2        38        78        56        50        71       111         9
3         9        92        18        46        15       111        18
4        17        30        11        45        29        28        12

  feature_7 feature_8 feature_9 feature_10 feature_11 feature_12 feature_13  \
0         1        11        45         45         47         18         56
1         1        62        45         15        111          2         48
2         1        56        96         12        111          9         49
3         4        58        48         15        111         19        137
4        13        18        45         29         48         12         46

  feature_14 feature_15  target
0          0          1       1
1          0          0       0
2          1          1       0
3          0          0       0
4          1          1       1
  feature_0 feature_1 feature_2 feature_3 feature_4 feature_5 feature_6  \
0        14        30        62        47        45       111         2
1        38        58        11        45        37        28        20
2        38        30        63        45        45        47        12
3        64        30        11        91        44        48        12
4        38        23        37        50        32        64        20

  feature_7 feature_8 feature_9 feature_10 feature_11 feature_12 feature_13  \
0        18        62        39         45         13          2         45
1        19        62        45         37         20         20         46
2         4        63        45         45         47          8         45
3        13        13        91         44        111         18         46
4        19        62        50         32        108         20        137

  feature_14 feature_15  target
0          1          1       1
1          1          0       0
2          0          1       0
3          0          1       1
4          1          0       1

In [12]:
for x in range(len(test_list)):
    train = train_list[x]
    test = test_list[x]# remove first 2 data points  [:,2:test_dataset1.shape(1)]
    cols = train.shape[1]
    train = train[:, 2:cols]
    test = test[:, 2:cols]
    if cols > 20:
        hide_meta_data = cols - 20
    else:
        hide_meta_data = 0
    umeta_end = 8
    rmeta_end = 16
    umeta_hide_end = umeta_end + hide_meta_data
    rmeta_hide_end = rmeta_end + hide_meta_data  
    
    
    #split x(input) and y(output) from train and test
    #output are the last 4 digits
    inputs= cols -4
    
    x_train = train[:, 0:inputs]
    y_train = train[:, inputs:cols]
    y_train = y_train.astype(int) #sets y_train into int
    
    x_test = test[:, 0:inputs]
    y_test = test[:, inputs:cols]
    y_test = y_test.astype(int)
    
    x_train = np.delete(x_train, slice(umeta_end, umeta_hide_end), 1)
    x_train = np.delete(x_train, slice(rmeta_end, rmeta_hide_end), 1)
    x_test = np.delete(x_test, slice(umeta_end, umeta_hide_end), 1)
    x_test = np.delete(x_test, slice(rmeta_end, rmeta_hide_end), 1)

In [11]:
print(test_list)
print(train_list)

[array([['716', '4256', '15', ..., '0', '1', '1'],
       ['4873', '4658', '10', ..., '1', '1', '1'],
       ['2489', '2', '12', ..., '0', '0', '0'],
       ...,
       ['1318', '1219', '12', ..., '0', '1', '0'],
       ['2830', '2', '8', ..., '0', '0', '0'],
       ['1989', '1761', '11', ..., '1', '1', '0']], dtype=object), array([['3031', '2889', '88', ..., '0', '0', '1'],
       ['5154', '2288', '88', ..., '1', '1', '0'],
       ['118', '285', '92', ..., '0', '0', '0'],
       ...,
       ['1723', '3686', '58', ..., '1', '0', '1'],
       ['2838', '9', '96', ..., '0', '0', '0'],
       ['4291', '1', '96', ..., '0', '0', '0']], dtype=object), array([['3434', '3410', '32', ..., '0', '1', '1'],
       ['89', '239', '39', ..., '0', '0', '0'],
       ['1395', '1361', '30', ..., '0', '1', '0'],
       ...,
       ['118', '385', '30', ..., '0', '0', '0'],
       ['2060', '1831', '61', ..., '1', '1', '0'],
       ['2982', '2952', '32', ..., '1', '0', '1']], dtype=object), array([['3530', '3257', '21', ..., '0', '1', '0'],
       ['2517', '3962', '20', ..., '0', '0', '1'],
       ['3186', '4460', '20', ..., '1', '0', '1'],
       ...,
       ['2630', '76', '19', ..., '0', '1', '1'],
       ['885', '794', '24', ..., '1', '0', '0'],
       ['849', '15', '20', ..., '0', '0', '0']], dtype=object), array([['111', '2356', '33', ..., '1', '1', '0'],
       ['929', '929', '18', ..., '1', '0', '0'],
       ['4356', '6437', '7', ..., '1', '1', '1'],
       ...,
       ['2181', '316', '18', ..., '1', '0', '0'],
       ['1479', '3534', '18', ..., '1', '1', '0'],
       ['731', '1312', '7', ..., '1', '0', '0']], dtype=object), array([['2400', '4181', '9', ..., '0', '0', '1'],
       ['562', '649', '23', ..., '1', '0', '0'],
       ['3440', '5601', '16', ..., '0', '1', '1'],
       ...,
       ['2232', '3660', '3', ..., '0', '0', '1'],
       ['1520', '2777', '9', ..., '1', '1', '0'],
       ['2441', '3872', '1', ..., '0', '0', '1']], dtype=object), array([['2396', '2333', '14', ..., '1', '1', '0'],
       ['2838', '910', '38', ..., '0', '0', '1'],
       ['1841', '1875', '38', ..., '1', '1', '0'],
       ...,
       ['2328', '539', '9', ..., '1', '1', '0'],
       ['4420', '4', '14', ..., '0', '0', '0'],
       ['2553', '2505', '11', ..., '0', '0', '1']], dtype=object)]
[array([['1552', '3971', '11', ..., '0', '1', '0'],
       ['521', '519', '13', ..., '1', '0', '0'],
       ['376', '632', '12', ..., '1', '0', '0'],
       ...,
       ['177', '1', '11', ..., '0', '0', '0'],
       ['4676', '4704', '12', ..., '1', '1', '1'],
       ['4287', '4544', '11', ..., '0', '1', '1']], dtype=object), array([['222', '4835', '58', ..., '0', '1', '1'],
       ['3785', '3713', '88', ..., '1', '0', '1'],
       ['4936', '5138', '96', ..., '0', '1', '1'],
       ...,
       ['3352', '2032', '83', ..., '0', '0', '1'],
       ['3007', '3017', '83', ..., '0', '1', '1'],
       ['1198', '1663', '83', ..., '0', '1', '0']], dtype=object), array([['4246', '4435', '61', ..., '1', '1', '1'],
       ['2250', '2717', '64', ..., '0', '0', '1'],
       ['3633', '3807', '31', ..., '0', '1', '1'],
       ...,
       ['2386', '3781', '5', ..., '0', '0', '1'],
       ['2687', '8', '39', ..., '0', '0', '0'],
       ['3272', '3175', '32', ..., '1', '0', '1']], dtype=object), array([['3523', '3590', '20', ..., '0', '1', '1'],
       ['1856', '0', '24', ..., '0', '0', '0'],
       ['1169', '3428', '24', ..., '0', '1', '1'],
       ...,
       ['2117', '2181', '26', ..., '0', '1', '1'],
       ['1830', '1894', '5', ..., '1', '1', '0'],
       ['3192', '1764', '19', ..., '1', '1', '1']], dtype=object), array([['1256', '1802', '5', ..., '1', '1', '1'],
       ['2108', '1100', '7', ..., '0', '0', '0'],
       ['560', '0', '7', ..., '0', '0', '0'],
       ...,
       ['3308', '1014', '108', ..., '1', '0', '0'],
       ['2596', '3935', '19', ..., '0', '0', '1'],
       ['3554', '936', '10', ..., '0', '0', '0']], dtype=object), array([['4034', '191', '8', ..., '0', '1', '1'],
       ['2758', '4779', '3', ..., '1', '0', '1'],
       ['2907', '4583', '20', ..., '1', '0', '1'],
       ...,
       ['1251', '843', '20', ..., '0', '1', '1'],
       ['787', '1403', '8', ..., '1', '0', '0'],
       ['294', '143', '1', ..., '0', '0', '0']], dtype=object), array([['1793', '2099', '38', ..., '1', '1', '0'],
       ['3361', '17', '17', ..., '0', '0', '0'],
       ['5058', '5011', '38', ..., '1', '1', '1'],
       ...,
       ['2917', '3033', '38', ..., '0', '0', '1'],
       ['2539', '716', '24', ..., '0', '0', '1'],
       ['1753', '1760', '11', ..., '1', '1', '0']], dtype=object)]

Train DataFrame 1:
      col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0        11     3   106    35     6     8   110    47     3     8    110
1        13    21   106    12     3    34   110    82     3    82    110
2        12     3   106    12    10    57    97    82    10    82     97
3        11   103     5    35    26    57    20     9    29    57      5
4        10    30    21    75    38    57    97    32    38    57      5
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
15623    11   103     7    70    40    57    85    82     3     8    110
15624    11   106   106    70     3    26    97     8    29     8      5
15625    11   106     7    62     6    75    85    47    29    53     15
15626    12     2     5    12     6    26   110    55     6    26    119
15627    11   103     4    51    40    34    52    32    40    34     72

      col_11 col_12 col_13 col_14 col_15 col_16 col_17
0          5      9    125      1      0      1      0
1         45     19     86      0      1      0      0
2          3     19    125      0      1      0      0
3         26     32     91      1      1      0      1
4         20     41    125      1      0      1      1
...      ...    ...    ...    ...    ...    ...    ...
15623     45     32     91      0      0      0      0
15624     20     32     85      0      0      1      0
15625      3     40    125      0      0      0      0
15626     28     40     85      0      1      1      1
15627     28      9     86      1      0      1      1

[15628 rows x 18 columns]
Test DataFrame 1:
     col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0       15   106   106    70     6    26    85    90     6    26     85
1       10   106     7    62     6    26   110    55     6    26      5
2       12   110     5    42     3    74    97    90    29    66     97
3       11    30     5    75     3    75    52    82     3    75     92
4       11   110   106    76     6    57    15    52    38    52     72
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
3902    10    21     4    35     6    66   110    82     8    66    110
3903    12    21     7    19     3    26   110     9     3    26     72
3904    12   106    97    42    26    26    97     8     3     8     72
3905     8    44    44    75     3    75    85    32    29    66     97
3906    11    21     7    75    10    74    52    90     3    74     92

     col_11 col_12 col_13 col_14 col_15 col_16 col_17
0        20     19     40      1      0      1      1
1         3     41    134      0      1      1      1
2        45     19     91      0      0      0      0
3         3     19    125      1      0      1      1
4        20     23     86      0      0      1      0
...     ...    ...    ...    ...    ...    ...    ...
3902      4     19    134      1      1      0      0
3903      4     19    134      0      1      1      1
3904     25     23     86      0      0      1      0
3905     45     19     91      0      0      0      0
3906     20     19    125      0      1      1      0

[3907 rows x 18 columns]
Train DataFrame 2:
      col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0        58    77     9    36    11     6     8    57     7     7     31
1        88    40     9    71     5    12     8    19     5    12      8
2        96    61    40    36    11    81    35    23     7     7     33
3        92    72    10    71     6    12    32    54     6    12     31
4        92    77     7    71     8     6    34    23     8     6     23
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
26041    39    75     9    58     8    89     8    54     8    89     54
26042    83    75    40    26     8    11    70    54    12    11     70
26043    83    40    35    20    10    12    70    24     7    12     70
26044    83    72    35    71     5    81    35    19     6    75     57
26045    83    70    10    20     6    22    35    68     6    22     31

      col_11 col_12 col_13 col_14 col_15 col_16 col_17
0         11     52     72      1      0      1      1
1          5     25     22      0      1      0      1
2         11     20     11      1      0      1      1
3          6     63      1      0      1      1      0
4          5     20      1      1      0      0      0
...      ...    ...    ...    ...    ...    ...    ...
26041      7     25      1      1      0      0      0
26042      7     63     24      1      0      0      1
26043      7     54     24      1      0      0      1
26044      5     63     11      1      0      1      1
26045     10     25     22      1      0      1      0

[26046 rows x 18 columns]
Test DataFrame 2:
     col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0       88    61     7    58     5     6    32    68     6    70     68
1       88    72    40    36     5    11    34    54     7    11     75
2       92    72    40    71     6    12    35    54     6    12     54
3       88    72     9    71     7    89    35    54     2    75     54
4       83    40    10    21     7    89    32    23     7    89     70
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
6506    83    72    36    36    10    22    38    23    12    22     70
6507    58    33     7    20    12    89    34    26     5    22     54
6508    58    75    35    71     8    22    38    24     2    22     38
6509    96    61    36    20     7    22    35    19    11    12     23
6510    96    72   117    20     5    81    34    68     5    11     57

     col_11 col_12 col_13 col_14 col_15 col_16 col_17
0         5     63     11      0      0      0      1
1         5     25     11      0      1      1      0
2         5     25     72      1      0      0      0
3         9     20     23      0      0      1      1
4         6     20     72      1      0      1      0
...     ...    ...    ...    ...    ...    ...    ...
6506     10     54     23      0      1      1      0
6507     10     20      1      0      0      0      0
6508      8     20     11      0      1      0      1
6509      7     25     11      0      0      0      0
6510      9     20     72      0      0      0      0

[6511 rows x 18 columns]
Train DataFrame 3:
     col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0       61    84     5    29    44   105     6    30     5    26     44
1       64    55   129    29    50   129     6    78    28    29     43
2       31    84     7    31    44   105     6    43    95    31     33
3       30    55    32    23    44    49     3    37   100    23     45
4        5    49    32    14    44    49    89    63    32    14     43
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
8767    32    51   126    29    44   114    51    65    65    29     44
8768     5    49     5    26    43   129    48    42     5    26     46
8769     5    49     5     1    50    49     6    30    65     1     56
8770    39    48   129    14    43    94    89    63   126    26     56
8771    32    48     5    26    63   112    51    78     5    46     63

     col_11 col_12 col_13 col_14 col_15 col_16 col_17
0       105      3      3      1      1      1      1
1        94     38      6      0      0      0      1
2       105      6      4      1      0      1      1
3        33     14      3      0      0      0      1
4       108    100      6      0      0      1      0
...     ...    ...    ...    ...    ...    ...    ...
8767     94     14      4      0      1      0      1
8768    114    100     25      0      0      1      0
8769    105     48      6      0      0      0      1
8770    108     38     15      0      0      0      0
8771    105      3     51      1      1      0      1

[8772 rows x 18 columns]
Test DataFrame 3:
     col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0       32    84    32    23    56   109    15    39    65    40     56
1       39    84     5    31    50    94    15    37     5    26     35
2       30    84   126    31    37    49     6    30   126    14     45
3       65    48     5    31    74    99    89    78   129    26     56
4       32    99    32    29    37   129    15     5    32    26     56
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
2187    14   123   131    26    37   129    48    39   131    26     37
2188    64    55     5     1    74   114     3    63   100     1     56
2189    30    49   126    23    50   105     3    42   126    35     50
2190    61    55    32    31    50    99     3     5    32    26     35
2191    32    51    32    29    50    99     6    64    65    29     50

     col_11 col_12 col_13 col_14 col_15 col_16 col_17
0       109      3     25      0      0      1      1
1        94     14     15      1      0      0      0
2        49     20      4      1      0      1      0
3       105      3     51      0      0      0      0
4       129     38      6      1      1      1      0
...     ...    ...    ...    ...    ...    ...    ...
2187     94     20     25      0      1      0      0
2188     33     20      3      0      0      0      1
2189    105      3      3      1      0      0      0
2190     99     49     84      1      1      1      0
2191    105     20      6      0      1      0      1

[2192 rows x 18 columns]
Train DataFrame 4:
      col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0        20    92    37    47     4    61    40    78    72     3     36
1        24    92    61    11     1     3    28     6    63     1      7
2        24    27    38    11    41     8     2    63    72     1     38
3        19   110    37    47     4    42     2    76    76    14     39
4        26    50    36    11    23     8    34    76    72     8     39
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
18062    19    92    36     6     1     6     2    63    63     3     47
18063    24    32    36    11     1    22    40    80    80    14     47
18064    26   110    37     7     4    22     2    34    34     3     36
18065     5    20    37     7    15    42    34     6     6    28     52
18066    19   110    37     6    41     6    33    34    34    14     39

      col_11 col_12 col_13 col_14 col_15 col_16 col_17
0          7      8     23      0      0      1      1
1         15      6      6      0      0      0      0
2         14     28     33      0      0      1      1
3          4      8     20      1      1      0      1
4          1      6     20      1      0      1      1
...      ...    ...    ...    ...    ...    ...    ...
18062     18     47     33      1      1      1      1
18063     40     60      6      1      0      0      1
18064      1     28      6      0      0      1      1
18065     21      8     20      1      1      1      0
18066     21      8     11      1      1      1      1

[18067 rows x 18 columns]
Test DataFrame 4:
     col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0       21    32    38    43    15    22     2     6     6    40     37
1       20    92    61    43    23     3     2    80    80    40     57
2       20    20    66     6     1     6    20     2     2     1     39
3       24    32    66    43     4     3    28     6    63    12      7
4       23    32    66    14     1     8    20    78    63    12      7
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
4511    21    92    12     7    23    61    20    34    34    30     37
4512    21    20    12     6     1     6     2    34    80     3     46
4513    19    27    36     6     4     6    33    72    72    12     37
4514    24    32    36    47    21    42     2    76    76    14     39
4515    20    50    61    47    23    22    40    76    72    12     37

     col_11 col_12 col_13 col_14 col_15 col_16 col_17
0        18     28     20      1      0      1      0
1        21     16     23      1      0      0      1
2         1     60     33      1      1      0      1
3         4     28     20      0      0      0      0
4         4     16      6      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...
4511      4     28      6      0      0      0      1
4512     16     47     20      0      0      1      1
4513     40     47     20      0      0      1      1
4514     40     28     23      1      1      0      0
4515     18      8     30      0      0      0      0

[4516 rows x 18 columns]
Train DataFrame 5:
      col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0         5     8    34    13    18    56    27     3     1    35     26
1         7    59    55     7    83    34    52    18    46     2     56
2         7    59    22    40    83    34    52     3    60    40     60
3        33     9    55     7   104    56    17    85     1    68     55
4         5    88    55     7   104    34    52     3    79    95     27
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
22996     3     8    22    36    18    12    71    70    18    18     56
22997     7    59    55    13    18    34     1    12    12    61     26
22998   108    50    55    36    18    56    24    12    12    11     60
22999    19    50    55    36   102    57    52    60    60   137     27
23000    10    88    38    15   104    34     1     3    12    68     60

      col_11 col_12 col_13 col_14 col_15 col_16 col_17
0          4     65     17      1      1      1      1
1         34     18      5      1      0      0      0
2         26     35     56      0      0      0      0
3         47      3     55      1      1      1      1
4         47     35     55      0      0      0      0
...      ...    ...    ...    ...    ...    ...    ...
22996     54     35     56      1      0      1      1
22997      4     18     17      0      1      0      0
22998     54     55     51      1      1      0      0
22999     54     34     51      1      0      0      1
23000     46      3      5      1      0      0      0

[23001 rows x 18 columns]
Test DataFrame 5:
     col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0       33    50    20    13   102    34     1     7    60     2     60
1       18     9    33    40    18    56     1    46    46    95     27
2        7    88    33    13    18    34    24     3    79     2     27
3       18     8    55    15    42    12    17     7     7   137     29
4       18     9    33     7    83    12    17    70    70    61     26
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
5745    21    88    33    13   104     7    24     3     3     5     26
5746    19    59    20     7    42    34    17    79    79    68     25
5747    18    15    38     7    18    34    17    18    18     2     56
5748    18    15    20    15   102     5    27    46    79     2     25
5749     7     8    22    13    18    56     1     3     3     2     60

     col_11 col_12 col_13 col_14 col_15 col_16 col_17
0        47     34      5      0      1      1      0
1        47     35      5      1      1      0      0
2         4      3     51      1      1      1      1
3        46     34     17      0      1      1      1
4        46     35     49      0      1      0      0
...     ...    ...    ...    ...    ...    ...    ...
5745     26     35     17      0      1      0      0
5746     26     34      5      0      0      1      0
5747     47     65      5      0      1      0      0
5748     47     18     49      0      1      1      0
5749      4     34     56      1      1      0      0

[5750 rows x 18 columns]
Train DataFrame 6:
      col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0         8    17    98    14    50    11    18   132    47    53    132
1         3    47    28     6     2    41    20    71    47    20     75
2        20     1   100    12    20     6    17   114    54    17    105
3         8    47    20    10    50    11    14    16    54    56     74
4         4    79    20    11    20    41    17    71    47    63     71
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
16022     1     1    20    14    53    40    14   105     7    14    105
16023    20    84   100    14    32     6    18   105    22    56    105
16024    20    17    32     9    61    12    14   105     1    56     75
16025     8     1   100    12    20    11     5    74    54    63     88
16026     1     1    28    10    53    41    17    71    22    71     71

      col_11 col_12 col_13 col_14 col_15 col_16 col_17
0         18     67      9      1      0      1      1
1         39     36     47      0      1      0      1
2         56     44     22      0      1      0      1
3         20     44     14      0      0      0      0
4         17     36     47      1      0      0      0
...      ...    ...    ...    ...    ...    ...    ...
16022     39    110     22      1      0      0      1
16023     14     44     13      0      0      1      0
16024     14     42     22      1      0      1      1
16025      5     44     22      1      1      0      0
16026     17     67     13      1      0      0      0

[16027 rows x 18 columns]
Test DataFrame 6:
     col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0        9    17    98    10    61    12    14   105    47    14    105
1       23    21    20    10    61    41    18    71     1    36     75
2       16    20   100    10    25    22    49    71    22    14     79
3        3    21    32    13    53    16    17   114    16    14     79
4       20    84    28    13    25    12    14    88     1    14     88
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
4001     1     1    28    11    61    12    14    14     1    14     14
4002     9    47    28     2    20    40    49    71    22    56     74
4003     3     1     2     2    50     6    23    71     7    23     71
4004     9    17    20    10    50     6    17    16     1    56     16
4005     1     1   100    13    75    12    63    14     1    63     14

     col_11 col_12 col_13 col_14 col_15 col_16 col_17
0        64     18     13      1      0      0      1
1        18     44     13      0      1      0      0
2        39     67     14      0      0      1      1
3        56     36     22      0      0      1      1
4        39     36     14      1      0      0      1
...     ...    ...    ...    ...    ...    ...    ...
4001     14     42     13      1      0      1      1
4002     49     44     22      0      0      0      0
4003      5     18     47      0      0      0      1
4004     14     44     13      0      1      1      0
4005      5     67     33      1      0      0      1

[4006 rows x 18 columns]
Train DataFrame 7:
      col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10  \
0        38    58    11    56    45    47    18     1    11    45     45
1        17    23    58    47    47   111     2     1    62    45     15
2        38    78    56    50    71   111     9     1    56    96     12
3         9    92    18    46    15   111    18     4    58    48     15
4        17    30    11    45    29    28    12    13    18    45     29
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
10147    24    22    62    50    29    64    18    18    62    46     29
10148    38    82    58    56    37   111     9    19    19    48     44
10149    38    22    11    45    71    64     8     4    61    45     71
10150    24    30    63    50    71    38     2    13    62    46     71
10151    11    17    11    50    45    91     5     1    11    91     45

      col_11 col_12 col_13 col_14 col_15 col_16 col_17
0         47     18     56      0      1      1      0
1        111      2     48      0      0      0      0
2        111      9     49      1      1      1      1